services:
  postgres:
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    networks:
      first:
        ipv4_address: 10.100.11.11
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kanboard_db_user
      POSTGRES_PASSWORD: kanboard_db_password
      PGDATA: /var/lib/postgresql/data/pgdata
  backend:
    image: kanban-board-backend:2.0-compose
    build: ./backend
    restart: unless-stopped
    networks:
      first:
        ipv4_address: 10.100.11.12
      second:
        ipv4_address: 10.100.12.12
    volumes:
      - ./backend/.env:/kanban-board/kanban-server/.env:ro
    ports:
      - "3080:3080"
  frontend:
    image: kanban-board-frontend:2.0-compose
    build: ./frontend
    restart: unless-stopped
    networks:
      second:
        ipv4_address: 10.100.12.13
    volumes:
      - ./frontend/kanban.conf:/etc/nginx/conf.d/kanban.conf:ro
    ports:
      - "8080:8080"

networks:
  first:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.11.0/24
  second:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.12.0/24